theme: minima
title: The gardeners blog
author: jthien
email: joerg.thienenkamp@gmail.com
description: What if you needed food and have 4 month time to let it grow? You can let  it grow in you garden. Crazy? Not at all!

# social links
twitter_username: jthien
github_username: jthien

show_excerpts: true # set to false to remove excerpts on the homepage
